name: Compare Files
# 定时触发工作流：每周一的00:00 UTC时间执行
on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一00:00执行 (UTC时间)
  push:
    branches:
      - main  # 当代码推送到main分支时触发

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    # 检出最新的仓库代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 安装所需的 Python 包（如有需要）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 安装你需要的库，例如 requests
        pip install requests

    # 运行 Python 脚本进行文件比对
    - name: Run file compare script
      run: |
        python compareRules.py  # 执行比对文件的脚本

    # 将比对结果提交到仓库（只有在有变更时才提交）
    - name: Commit and push generated files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: file comparison result"
          git push
        fi
